name: Kaggle-NYTaxiFare

channels:
  - conda-forge

dependencies:
  - python=3.7
  - jupyter
  - flask
  - flask-cors
  - requests
  - pandas
  - scikit-learn
  - joblib
  - BeautifulSoup4
  - lxml
  - geopy